### PR TITLE
Fixes #14 Incorrect artifact, project configurations in POMs

### LINKED ISSUE #14: Incorrect artifact, project configurations in POMs
Execute mvn package is fail. I fixed this on fork https://github.com/softfly/jakartaee-tutorial-examples

```
[INFO] Scanning for projects...
Downloading from snapshot-repository.java.net: https://maven.java.net/content/repositories/staging/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloading from releases-repository.java.net: https://maven.java.net/content/repositories/releases/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom (13 kB at 30 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:archetypes:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\archetypes\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:archetypes:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:batch:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\batch\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 16, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:batch:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:case-studies:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\case-studies\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 17, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:case-studies:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 17, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:cdi:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\cdi\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 16, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:cdi:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:concurrency:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\concurrency\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:concurrency:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:connectors:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\connectors\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 21, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:connectors:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 21, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:ejb:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\ejb\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:ejb:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:jaxrs:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jaxrs\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:jaxrs:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:jaxws:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jaxws\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:jaxws:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:jms:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jms\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 17, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:jms:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 17, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:persistence:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\persistence\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 20, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:persistence:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:security:8.1-SNAPSHOT (D:\java\projects\jakartaee-tutorial-examples\security\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 22, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:security:8.1-SNAPSHOT: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 22, column 13
[WARNING] 'parent.relativePath' of POM org.glassfish.javaeetutorial:web:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\web\pom.xml) points at jakarta.tutorial:examples instead of org.glassfish.javaeetutorial:javaeetutorial, please verify your project structure @ line 16, column 13
[FATAL] Non-resolvable parent POM for org.glassfish.javaeetutorial:web:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13
 @
[ERROR] The build could not read 13 projects -> [Help 1]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:archetypes:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\archetypes\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:archetypes:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:batch:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\batch\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:batch:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:case-studies:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\case-studies\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:case-studies:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 17, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:cdi:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\cdi\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:cdi:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:concurrency:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\concurrency\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:concurrency:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:connectors:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\connectors\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:connectors:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 21, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:ejb:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\ejb\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:ejb:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:jaxrs:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jaxrs\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:jaxrs:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:jaxws:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jaxws\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:jaxws:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:jms:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\jms\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:jms:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 17, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:persistence:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\persistence\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:persistence:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:security:8.1-SNAPSHOT (D:\java\projects\jakartaee-tutorial-examples\security\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:security:8.1-SNAPSHOT: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 22, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project org.glassfish.javaeetutorial:web:[unknown-version] (D:\java\projects\jakartaee-tutorial-examples\web\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.glassfish.javaeetutorial:web:[unknown-version]: Could not find artifact org.glassfish.javaeetutorial:javaeetutorial:pom:8.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

### PR DESCRIPTION
**Pull request by softfly**
Fixes #14

### CODE REVIEW

**Comment by bshannon** [comment]
Sorry, I fixed #14 myself before seeing this PR.

I see this PR also changes all the package names, which is good.

Can you update this PR to sync with the latest changes in the repo and resubmit it,
making sure to include the Signed-Off-By header (git commit -s)?  Thanks.

**Comment by softfly** [comment]
Ready

**Comment by softfly** [comment]
Ready

**Comment by softfly** [comment]
> Ok, I now see what you've done to the commit history. You've pulled in the
> entire history from the javaee version of the repository. I'm not going merge this.
> It would require IP review of every commit from the previous history. I'm not
> even going to consider that.
> 
> If you want _your_ changes to be merged, you need to redo them all on top
> of the current eclipse-ee4j version of the repository, without including anyone
> else's changes.
> 
> Sorry.

Ready

**Pull request merged**
