### PR TITLE
Migrate to Jakarta EE 9

### PR DESCRIPTION
**Pull request by hussainnm**

### CODE REVIEW

**Comment by hussainnm** [comment]
Just a note: I have hit a block in compiling the **persistence/roster** and **case-studies/dukes-tutoring** projects because the metamodels are not being generated during the compile phase. If somebody has any idea about this please drop a comment on how to resolve this. I will push the **javax -> jakarta** changes but it will not build.

**Comment by hussainnm** [comment]
[CategoryController](../blob/master/case-studies/dukes-forest/dukes-store/src/main/java/com/forest/web/CategoryController.java) - `javax.faces.bean.ManagedBean` -> `jakarta.inject.Named`
Add `JsonbTransient` annotation along with `XmlTransient` to prevent recursive references
Remove unnecessary dependency in **dukes-payment**
Partially rollback changes from 0183094
Reorder modules - bring **dukes-store** before **dukes-payment**

**Comment by hussainnm** [comment]
**cdi:**
- Remove unnecessary `UserBean.java` in **cdi/simplegreeting**

**concurrency:**
- Partially rollback changes from 0183094
- Define `resource-env-ref` in `web.xml` of **concurrency/jobs** (alternatively `@Resource(name)` can be used instead of `@Resource(lookup)` to skip defining it in web.xml)

**Comment by hussainnm** [comment]
**connectors/trading:**
- Define `resource-ref` for JNDI name in web.xml to resolve deployment failures
- Change `@ConnectionDefinition` `connection` and `connectionFactory` classes to `TradeConnection` and `TradeConnectionFactory` respectively

This fixes #11

**Comment by hussainnm** [comment]
**ejb/standalone**
- Requires **glassfish-embedded-all-6.0.0.jar** in maven central

**Comment by hussainnm** [comment]
> Just a note: I have hit a block in compiling the **persistence/roster** and **case-studies/dukes-tutoring** projects because the metamodels are not being generated during the compile phase. If somebody has any idea about this please drop a comment on how to resolve this. I will push the **javax -> jakarta** changes but it will not build.

I found the issue as to why the metamodel classes are not being generated:
EclipseLink treats all `jakarta.*` packages as excluded from annotation processing.

Only solution is change the root package from `jakarta` to something eg., `jakartaee` or `ee.jakarta` 

This change should impact only the above examples

**Comment by hussainnm** [comment]
All examples are migrated to Jakarta EE 9.

**Comment by edbratt** [comment]
This is awesome. Are you looking at the Tutorial text in jakartaee-documentation or, would you like someone else to have a run at the changes needed in that project? I can help, or find someone to help with that -- if you aren't planning to work on that. But what is here looks wonderful.

**Comment by hussainnm** [comment]
Thanks @edbratt. I have not yet started looking into to the Tutorial text. I don't expect too many changes as most of the code snippets will remain the same. I have been following the tutorial to test each example and everything is working.

**Comment by edbratt** [comment]
I believe that the changes would primarily be in the example code listings -- switching javax to jakarta -- and I have noticed that some of the XML NS references are quite out of date. Were it not for the smattering of legitimate javax references (referring to classes that did not migrate as part of Java EE to Jakarta), most of these could be fixed with a straightforward 'sed' script. Some other changes include -- updating to reflect that other implementations can be compatible implementations -- and changing from Java EE 9 to Jakarta EE 9 -- probably a few other similar type changes.

**Review by keilw — COMMENTED** [review]
This might be OK but before approving or merging it, shouldn't there be a tag for a Jakarta EE 8 compliant verison first? @ivargrimstad what do you think and could you tag it?

**Comment by ggam** [comment]
Great work @hussainnm!!

> Only solution is change the root package from jakarta to something eg., jakartaee or ee.jakarta

I think we should reserve the `jakarta` top-level package to specifications. What about `ee.jakarta.tutorial` for all the examples?

**Comment by hussainnm** [comment]
+1 for `ee.jakarta.tutorial`

I will create a separate PR later for the namespace change.

**Comment by ggam** [comment]
@hussainnm I have just opened a PR for the tutorial: https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/238

**Comment by hussainnm** [comment]
Resolved merge conflicts with master branch.

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Let's just merge this in and get things moving again ;)

**Pull request merged**
